[package]
name = "futures_codec"
version = "0.1.1"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
description = "Utilities for encoding and decoding frames using `async/await`"
license = "MIT"
keywords = ["codec", "async", "await"]
categories = ["asynchronous", "network-programming"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.14"